permalink: /:year/:month/:day/:title.html
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: heaven旅行包
  email: chengfangpeng00@gmail.com
  link: http://chengfangpeng.com
  weibo: http://weibo.com/havencfp
  github: http://github.com/chengfangpeng

# 站点信息
title: heaven's blog
description: heaven旅行包的博客
url: http://chengfangpeng.com
rss_url: /pages/atom.xml

weibo:    havencfp
github:   chengfangpeng

#多说配置
duoshuo_short_name: xray

#Google站内搜索
google_cx: g***

# avatar头像及Favicon
avatar: http://img3.imgtn.bdimg.com/it/u=888205968,2778669945&fm=21&gp=0.jpg
favicon: http://img3.imgtn.bdimg.com/it/u=888205968,2778669945&fm=21&gp=0.jpg
